// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yeraihlfudoedjhmisdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllcmFpaGxmdWRvZWRqaG1pc2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NzI2NTMsImV4cCI6MjA1OTQ0ODY1M30.mAmwJV1T_vn1UstxYz1ItetIjYgsIYP2hT-9bHTEQZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);