// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtuqqbdsflpfycgwtwao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10dXFxYmRzZmxwZnljZ3d0d2FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMDE4MjMsImV4cCI6MjA2MTg3NzgyM30.UgNp11N3thlu6H7b88hgNNvq9NTSgGDGTHon4cXmszs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);